//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipSiparis.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderHistory = new HashSet<OrderHistory>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public decimal Amount { get; set; }
        public string PayMeth { get; set; }
        public string UserName { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderDateString { get { return EstArrival.ToString("dd/MM/yyyy"); } }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> TerminDate { get; set; }
        public string TerminDateString { get { return EstArrival.ToString("dd/MM/yyyy"); } }

        public string AtchPath { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
        public string Decision { get; set; }
        public decimal Price { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime EstArrival { get; set; }
        public string EstArrivalString { get { return EstArrival.ToString("dd/MM/yyyy"); } }
        public string Note { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentDateString { get { return EstArrival.ToString("dd/MM/yyyy"); } }

        public string AtchName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        public List<SelectListItem> CategoryList { get; set; }
        public List<SelectListItem> BrandList { get; set; }
        public List<SelectListItem> DecisionList { get; set; }
        public List<SelectListItem> AttachmentList { get; set; }
        public List<SelectListItem> UserList { get; set; }
        public List<SelectListItem> PayMethList { get; set; }

    }
}
