//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipSiparis.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderHistories = new HashSet<OrderHistory>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public decimal Amount { get; set; }
        public int PayMethID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> TerminDate { get; set; }
        public Nullable<int> AtchID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> DecisionID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime EstArrival { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Decision Decision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual User User { get; set; }

        public List<SelectListItem> CategoryList { get; set; }
        public List<SelectListItem> BrandList { get; set; }
        public List<SelectListItem> DecisionList { get; set; }
        public List<SelectListItem> AttachmentList { get; set; }
        public List<SelectListItem> UserList { get; set; }
        public List<SelectListItem> PayMethList { get; set; }
    }
}
